name: "NGINXaaS for Azure Deployment Sync"
description: "Sync NGINX configuration from a git repo and/or certificates from an Azure Key Vault to an NGINXaaS for Azure deployment"
inputs:
  subscription-id:
    description: "The Azure subscription ID of the NGINXaaS for Azure deployment."
    required: true
  resource-group-name:
    description: "The resource group of the NGINXaaS for Azure deployment."
    required: true
  nginx-deployment-name:
    description: "The name of the NGINXaaS for Azure deployment."
    required: true
  nginx-config-directory-path:
    description: 'The NGINX configuration directory path relative to the root of the Git repository, example: "config/".'
    required: false
  nginx-root-config-file:
    description: >
      'The root NGINX configuration file path relative to the NGINX configuration directory in the Git repository, example: "nginx.conf".'
    required: false
    default: "nginx.conf"
  transformed-nginx-config-directory-path:
    description: >
      'The transformed absolute path of the NGINX configuration directory in NGINXaaS for Azure deployment, example: "/etc/nginx/".
      If the "include" directive in the NGINX configuration files uses absolute paths, the path transformation
      can be used to overwrite the file paths when the action synchronizes the files to the NGINXaaS for Azure deployment.'
    required: false
    default: ""
  nginx-certificates:
    description: 'An array of JSON objects each with keys nginx_cert_name, keyvault_secret, certificate_virtual_path and key_virtual_path. Example: [{"certificateName": "server1", "keyvaultSecret": "https://...", "certificateVirtualPath": "/etc/ssl/certs/server1.crt", "keyVirtualPath": "/etc/ssl/certs/server1.key"  }, {"name": "server2", "keyvaultSecret": "https://...", "certificateVirtualPath": "/etc/ssl/certs/server2.crt", "keyVirtualPath": "/etc/ssl/certs/server2.key"  }] '
    required: false
  debug:
    description: "Enable/Disable debug output."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: "Synchronize NGINX certificate(s) from the Git repository to an NGINXaaS for Azure deployment"
      run: ${{github.action_path}}/src/deploy-certificate.sh --subscription_id=${{ inputs.subscription-id }} --resource_group_name=${{ inputs.resource-group-name }} --nginx_deployment_name=${{ inputs.nginx-deployment-name }} --certificates=${{ toJSON(inputs.nginx-certificates) }} --debug=${{ inputs.debug }}
      if: ${{ inputs.nginx-certificates != '' }}
      shell: bash
    - name: "Synchronize NGINX configuration from the Git repository to an NGINXaaS for Azure deployment"
      run: ${{github.action_path}}/src/deploy-config.sh --subscription_id=${{ inputs.subscription-id }} --resource_group_name=${{ inputs.resource-group-name }} --nginx_deployment_name=${{ inputs.nginx-deployment-name }} --config_dir_path=${{ inputs.nginx-config-directory-path }} --root_config_file=${{ inputs.nginx-root-config-file }} --transformed_config_dir_path=${{ inputs.transformed-nginx-config-directory-path }} --debug=${{ inputs.debug }}
      if: ${{ inputs.nginx-config-directory-path != '' }}
      shell: bash
