name: Nginx Config Dry Run

on: 
  pull_request:
    paths:
      - '/Users/a.sanjannagari/nginx-for-azure-deploy-action/test/configs/multi/nginx.conf'  # Adjust the pattern to match the path of config files

jobs:
  config-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Run Nginx config dry runs
      run:
        sudo nginx -t -c /Users/a.sanjannagari/nginx-for-azure-deploy-action/test/configs/multi/nginx.conf